version: '3.8'
services:
#  site-commissions:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      args:
#        JAR_FILE: dispatcher-zhurzh-1.0.0.jar
#    ports:
#      - "8095:8090"
#    restart: always
#    container_name: site-commissions-zhurzh
#    environment:
#      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
#      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
#      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
#      SPRING_RABBITMQ_HOST: ${TARGET_HOST}
#      SPRING_RABBITMQ_PORT: ${SPRING_RABBITMQ_PORT}
#      SPRING_RABBITMQ_USERNAME: ${SPRING_RABBITMQ_USERNAME}
#      SPRING_RABBITMQ_PASSWORD: ${SPRING_RABBITMQ_PASSWORD}
#      SPRING_JPA_GENERATE_DDL: "true"
#      TARGET_HOST: ${TARGET_HOST}
#    deploy:
#      resources:
#        limits:
#          memory: 150M
#    logging:
#      options:
#        max-size: "10m"
#        max-file: "3"

  unified-services:
    build:
      context: .
      dockerfile: Dockerfile-all
    ports:
      - "8195:8195"  # app2
      - "9002:9002"  # app3
      - "9003:9003"  # app5
      - "9005:9005"  # app6
      - "9001:9001"  # app7
      - "9004:9004"  # app8
    restart: always
    container_name: unified-services
    volumes:
      - .:/app
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_RABBITMQ_HOST: ${TARGET_HOST}
      SPRING_RABBITMQ_PORT: ${SPRING_RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${SPRING_RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${SPRING_RABBITMQ_PASSWORD}
      SPRING_JPA_GENERATE_DDL: "true"
      TARGET_HOST: ${TARGET_HOST}
      DISPATCHER_STATIC_URL: ${DISPATCHER_STATIC_URL}
      BOT_TOKEN: ${BOT_TOKEN}
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: 500M
        reservations:
          cpus: '0.25'
          memory: 300M
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  app4:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JAR_FILE: dispatcher-1.2.3.jar
    ports:
      - "8090:8999"
    restart: always
    container_name: dispatcher
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_RABBITMQ_HOST: ${TARGET_HOST}
      SPRING_RABBITMQ_PORT: ${SPRING_RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${SPRING_RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${SPRING_RABBITMQ_PASSWORD}
      SPRING_JPA_GENERATE_DDL: "true"
      TARGET_HOST: ${TARGET_HOST}
      DISPATCHER_STATIC_URL: ${DISPATCHER_STATIC_URL}
      BOT_TOKEN: ${BOT_TOKEN}
      DISPATCHER_SERVER_PORT: 8999
    deploy:
      resources:
        limits:
          memory: 150M
    logging:
      options:
        max-size: "10m"
        max-file: "3"
