server.port=${DISPATCHER_SERVER_PORT}

bot.name=${BOT_NAME}
bot.token=${BOT_TOKEN}
bot.uri=${DISPATCHER_STATIC_URL}

server.ssl.enabled=false

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}