server.port=8195

cache.maxSize=10000


spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.generate-ddl=true

dispatcher.server.url=${DISPATCHER_STATIC_URL}

salt=hesh-124-salt-yes-true

# links to pictures
image.menu.url.ru=https://d.furaffinity.net/art/marzipan~/1705064470/1704766239.marzipan~_img_2860.jpg
image.menu.url.eng=https://d.furaffinity.net/art/marzipan~/1705064527/1704979243.marzipan~_img_2861.jpg