package com.zhurzh.commonjpa.entity;

public enum UserState { // состояния пользователя
    BASIC_STATE,
    WAIT_FOR_PHONENUMBER_STATE,
    WAIT_FOR_ID_KEY,
    // стажировка
    INTERN_PROGRESS_INIT,
    WAIT_FOR_LOCATION_STATE,
    WAIT_FOR_CHOOSE_DAY,
    WAIT,
    WAIT_FOR_WRITE_FEEDBACK_STATE,
    WAIT_FOR_CHOOSE_PERSON_FOR_FEEDBACK,
    WAIT_FOR_CHOOSE_PERSON_AT_FIRST_DAY,
    WAIT_FOR_SET_LEVEL,
    WAIT_FOR_SET_POST,
    WAIT_FOR_CHOOSING_LOCATION,
    WAIT_FOR_UP_LEVEL,
    WAIT_FOR_SET_LINKS,
    WAIT_FOR_CHOOSE_LINK,
    WAIT_FOR_SET_OPPORTUNITIES,
    WAIT_FOR_CHOOSE_OPPORTUNITIES,
    WAIT_FOR_CHOOSE_LIST_LOCATIONS,
    WAIT_FOR_CHOOSE_LIST_PERSONS,
    WAIT_FOR_PASS_EXAM,
    WAIT_FOR_PASS_EXAM_2,
    WAIT_FOR_CHOOSE_USER_POST,
    WAIT_FOR_CHOOSE_LEVEL_OR_POST,
    WAIT_FOR_UP_PERSON,
    WAIT_FOR_CHOOSE_USER_POST_FOR_UP_POST,
    WAIT_FOR_FEEDBACK,
    WAIT_FOR_FEEDBACK_2,
    GENERATION_LINKS_1,
    GENERATION_LINKS_2,
    GENERATION_LINKS_3,
    COACH_CHOOSE_MENTOR_FOR_UP,
     INTERN_WANT_PASS_EXAMS, INTERN_WANT_PASS_EXAMS_2, LEVEL_2_COACH_MAKE_POSSIBLE_GET_EXAMS, LEVEL_2_COACH_MAKE_BE_A_COACH_OF_MENTORS, INTERN_CAME_TO_FIRST_DAY, ORDER
    ,WAIT_FOR_CHOOSE_EXAMS_NAME,
    WAIT_FOR_CHOOSE_EXAMS_NAME_2,
    CHOOSING_MENTOR, WAIT_FOR_CHOOSE_PERSON_FOR_COFFEE, WAIT_FOR_CHOOSE_DAY_FOR_COFFEE, WAIT_FOR_CHOOSE_DAY_FOR_COFFEE_TO_CONFIRM, WAIT_FOR_NAME




}
