<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>Telegram-Bot-Zhurzh</artifactId>
        <groupId>com.zhuzh</groupId>
        <version>2.0.0</version>
    </parent>

    <groupId>com.zhurzh</groupId>
    <artifactId>node-faq-service</artifactId>
    <version>2.0.0</version>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-cache</artifactId>
        </dependency>

        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.zhurzh.node.NodeApplication</mainClass> <!-- Укажите полный путь к вашему основному классу -->
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
