<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>Telegram-Bot-Zhurzh</artifactId>
        <groupId>com.zhuzh</groupId>
        <version>2.0.0</version>
    </parent>
    <version>2.0.0</version>

    <artifactId>node</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.zhurzh</groupId>
            <artifactId>node-faq-service</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.zhurzh</groupId>
            <artifactId>node-order-service</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.zhurzh</groupId>
            <artifactId>node-price-list</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.zhurzh</groupId>
            <artifactId>node-start-service</artifactId>
            <version>2.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.7.3</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hibernate.orm</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>6.5.2.Final</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-amqp</artifactId>
        </dependency>

        <dependency>
            <groupId>com.zhuzh</groupId>
            <artifactId>common-rabbitmq</artifactId>
            <version>2.0.0</version>
        </dependency>

        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>2.3.1</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.zhurzh.node.NodeApplication</mainClass> <!-- Укажите полный путь к вашему основному классу -->
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
